blank_issues_enabled: false
contact_links:
  - name: Omar Yousef
    url: https://www.linkedin.com/in/mourra950/
    about: Contact Omar Yousef here
  - name: Omar Banna
    url: https://www.linkedin.com/in/omar-el-banna/
    about:  Contact Omar Elbanna here
  - name: Nada Amr
    url: https://www.linkedin.com/in/nada-amr/
    about: Contact Nada here
  - name: Adham Abdelmaksoud
    url: https://www.linkedin.com/in/adham-abdelmaksoud/
    about:  Contact Adham Abdelmaksoud here
  
  