name: Feauture Request
description: File a feature report issue
title: "[Feature]: "
labels: ["enhancment"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What feature to add
      description: Describe the feature you want to add using what tools
      placeholder: Explain the feature you want to add!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Milestone
      description: This feature is related to which issue
      options:
        - Milestone 1
        - Milestone 2 
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What labels is that issue related to
      multiple: true
      options:
        - Pytorch
        - Structure
        - Docs
        - Python
        - PyQt
        - SystemC
        - Cmake
        - Jinja
        - Enhancement 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Python
  