name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Ahoy sailor welcome to the world of issues where complaints are welcome"
        pr-message: "Ahoy ahoy greeting great programmer and thank you for contributing "
